AspNetCoreMvcSharedLocalization/Controllers/SetLanguageController.cs
namespace AspNetCoreMvcSharedLocalization.Controllers
{
    using System;

    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Localization;
    using Microsoft.AspNetCore.Mvc;

    public class SetLanguageController : Controller
    {
        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }
    }
}

AspNetCoreMvcSharedLocalization/Views/Shared/_Layout.cshtml
@using AspNetCoreMvcSharedLocalization.Resources

@inject LocService SharedLocalizer

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNetCoreMvcSharedLocalization</title>

    <link rel="stylesheet" href="~/css/vendor.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
</head>
<body>
    <nav class="bg-dark mb-4 navbar navbar-dark navbar-expand-md">
            <div class="navbar-header">

            <a asp-controller="Home" asp-action="Index" class="navbar-brand">CSE6602</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">@SharedLocalizer.GetLocalizedHtmlString("overview")</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="About">@SharedLocalizer.GetLocalizedHtmlString("about")</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Contact">@SharedLocalizer.GetLocalizedHtmlString("contact")</a>
                    </li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
    </nav>

    <div class="container body-content">
        @RenderBody()

        <footer>
            <hr />
            <nav class="navbar transparent navbar-inverse">
                <p>&copy; 2024 - CSE6602</p>

                @await Html.PartialAsync("_SelectLanguagePartial")
            </nav>
        </footer>

    </div>
    <script src="~/js/vendor.min.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>


    @RenderSection("Scripts", required: false)
</body>
</html>

AspNetCoreMvcSharedLocalization/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions
@using AspNetCoreMvcSharedLocalization.Resources
@inject LocService SharedLocalizer
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}

<div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    <form class="form-inline" id="selectLanguage" asp-controller="SetLanguage" asp-action="SetLanguage" asp-route-returnUrl="@Context.Request.Path" method="post" class="form-horizontal" role="form">
        <label class="form-label" style="padding-right:5px">@SharedLocalizer.GetLocalizedHtmlString("LANGUAGE"): </label>
        <div class="input-group">

            <select class="custom-select" name="culture" asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems"></select>
            <div class="input-group-append">
                <button type="submit" class="btn btn-outline-secondary">@SharedLocalizer.GetLocalizedHtmlString("SAVE")</button>
            </div>
        </div>
    </form>
</div>